markdown: redcarpet
permalink: /:categories/:title.html
url:
lsi: false
pygments: true
safe: true
auto: false

paginate: 8
paginate_path: "page:num"

# presonal config
domain: zbc.io
title: zbc.io
description: 一起来讨论技术吧！
author: Zhang Baicheng
email: zbc0512@163.com
github: zbcblog

config:
  js_dir:
  img_dir:
  css_dir:
